---
# Setup for installing Docker on Debian from the official Docker repo
#
# https://docs.docker.com/engine/install/debian/

- name: Uninstall non-official versions of packages (Debian)
  ansible.builtin.package:
    name:
      - containerd
      - docker
      - docker-engine
      - docker.io
      - runc
    state: absent

- name: Add official Docker repo (Debian, not Kali)
  when:
    - ansible_distribution | lower != "kali"
  block:
    - name: Install prerequisites so apt can use a repo over HTTPS (Debian, not Kali)
      ansible.builtin.package:
        name: "{{ apt_over_https_prerequisites }}"
    - name: Get official Docker repo GPG key (Debian, not Kali)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    - name: Add the official Docker repo (Debian, not Kali)
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Add official Docker repo (Kali)
  when:
    - ansible_distribution | lower == "kali"
  block:
    - name: Install prerequisites so apt can use a repo over HTTPS (Kali)
      ansible.builtin.package:
        name: "{{ apt_over_https_prerequisites }}"
    - name: Install prerequisites so apt can use DEB822 repos (Kali)
      ansible.builtin.package:
        name:
          - python3-debian
    - name: Add the official Docker repo (Kali)
      ansible.builtin.deb822_repository:
        components:
          - stable
        name: docker
        signed_by: https://download.docker.com/linux/debian/gpg
        suites:
          - bookworm
        uris:
          - https://download.docker.com/linux/debian
    - name: Update the package cache
      ansible.builtin.apt:
        update_cache: true
