---
# Setup for installing Docker on Debian from the official Docker repo
#
# https://docs.docker.com/engine/install/debian/

- name: Uninstall non-official versions of packages (Debian)
  ansible.builtin.package:
    name:
      - containerd
      - docker
      - docker-engine
      - docker.io
      - runc
    state: absent

- name: Install prerequisites so apt can use a repo over HTTPS
  ansible.builtin.package:
    name: "{{ apt_over_https_prerequisites }}"

# Debian Buster does not support DEB822 repos, so we have to treat it
# as a special case.
- name: Add official Docker repo (Debian Buster)
  when:
    - ansible_distribution_release == "buster"
  block:
    - name: Get official Docker repo GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ apt_distro }}/gpg
    - name: Add the official Docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ apt_distro | lower }} {{ apt_distro_release }} stable
    # ansible.builtin.apt_repository updates the package cache so
    # there is no need to do it explicitly.

- name: Add official Docker repo
  when:
    - ansible_distribution_release != "buster"
  block:
    - name: Install prerequisites so apt can use DEB822 repos
      ansible.builtin.package:
        name:
          - python3-debian
    - name: Add the official Docker repo
      ansible.builtin.deb822_repository:
        components:
          - stable
        name: docker
        signed_by: https://download.docker.com/linux/{{ apt_distro }}/gpg
        suites:
          - "{{ apt_distro_release }}"
        uris:
          - https://download.docker.com/linux/{{ apt_distro }}
    - name: Update the package cache
      ansible.builtin.apt:
        update_cache: true
