---
# The Ubuntu Docker images we are using
# (geerlingguy/docker-ubuntu1604-ansible:latest and
# geerlingguy/docker-ubuntu1804-ansible:latest) require a cache update
# before they can install anything.
- name: Group hosts by OS distribution
  hosts: all
  tasks:
    - name: Group hosts by OS distribution
      group_by:
        key: os_{{ ansible_distribution }}
- name: Update apt cache (Ubuntu)
  hosts: os_Ubuntu
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

# The Fedora Docker images we are using
# (geerlingguy/docker-fedora32-ansible:latest and
# cisagov/docker-fedora33-ansible:latest) require the dnf cache to
# be updated before they can successfully install anything.  At least,
# they keep giving this error if I don't update the dnf cache:
#
# No such file or directory: '/var/cache/dnf/metadata_lock.pid'
#
# Related to this, I see sporadic failures when updating the DNF cache.
# The fix is to ensure that systemd finishes initializing before updating
# the cache.  For details see:
# https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
- name: Update dnf cache (Fedora)
  hosts: os_Fedora
  pre_tasks:
    - name: Wait for systemd to complete initialization. # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: "'running' in systemctl_status.stdout"
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes
